<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240303140259 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE paiement ALTER COLUMN date_paiement TYPE TIMESTAMP WITHOUT TIME ZONE USING (CURRENT_DATE + date_paiement)');
    }
    
    
    
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE paiement ALTER date_paiement TYPE TIME(0) WITHOUT TIME ZONE');
    }
}
