<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240331134557 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE livraison (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_livraison TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quantite INT DEFAULT NULL, fournisseur_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A60C9F1F670C757F ON livraison (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_A60C9F1FF347EFB ON livraison (produit_id)');
        $this->addSql('ALTER TABLE livraison ADD CONSTRAINT FK_A60C9F1F670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livraison ADD CONSTRAINT FK_A60C9F1FF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE livraison DROP CONSTRAINT FK_A60C9F1F670C757F');
        $this->addSql('ALTER TABLE livraison DROP CONSTRAINT FK_A60C9F1FF347EFB');
        $this->addSql('DROP TABLE livraison');
    }
}
